#!/usr/bin/env bash

echo -e "\e[39m   1A   2A                                         3A  4A  5A  6A  7A  8A "
echo "  +---+                                                               +---+ "
echo -e "\e[39m1 |\e[34mH  |                                                               \e[1;36m|He | "
echo "  |---+---+                                       +-------------------+---| "
echo -e "\e[39m2 |\e[31mLi \e[1;33m|Be |                                       \e[33m|B  \e[35m|C  |N  |O  \e[1;34m|F  \e[1;36m|Ne | "
echo "  |---+---|                                       |---+---+---+---+---+---| "
echo -e "\e[39m3 |\e[31mNa \e[1;33m|Mg |\e[39m3B  4B  5B  6B  7B |    8B     |1B  2B \e[1;31m|Al \e[33m|Si \e[35m|P  |S  \e[1;34m|Cl \e[1;36m|Ar | "
echo "  |---+---+---------------------------------------+---+---+---+---+---+---| "
echo -e "\e[39m4 |\e[31mK  \e[1;33m|Ca \e[1;31m|Sc |Ti |V  |Cr |Mn |Fe |Co |Ni |Cu |Zn |Ga \e[33m|Ge |As \e[35m|Se \e[1;34m|Br \e[1;36m|Kr | "
echo "  |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---| "
echo -e "\e[39m5 |\e[31mRb \e[1;33m|Sr \e[1;31m|Y  |Zr |Nb |Mo |Tc |Ru |Rh |Pd |Ag |Cd |In |Sn \e[33m|Sb |Te \e[1;34m|I  \e[1;36m|Xe | "
echo "  |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---| "
echo -e "\e[39m6 |\e[31mCs \e[1;33m|Ba \e[39m|LAN\e[1;31m|Hf |Ta |W  |Re |Os |Ir |Pt |Au |Hg |Tl |Pb |Bi \e[33m|Po \e[1;34m|At \e[1;36m|Rn | "
echo "  |---+---+---+-----------------------------------------------------------+"
echo -e "\e[39m7 |\e[31mFr \e[1;33m|Ra \e[39m|ACT| "
echo "  +---+---+---+"
echo -e "\e[39m              +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+ "
echo -e "\e[39m   Lanthanide \e[1;35m|La |Ce |Pr |Nd |Pm |Sm |Eu |Gd |Tb |Dy |Ho |Er |Tm |Yb |Lu | "
echo -e "\e[39m              |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---| "
echo -e "\e[39m   Actinide   \e[1;32m|Ac |Th |Pa |U  |Np |Pu |Am |Cm |Bk |Cf |Es |Fm |Md |No |Lw | "
echo -e "\e[39m              +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+ "
echo ""